apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80      # The port the Service itself will listen on (internal to cluster)
      targetPort: 3000 # <--- CHANGE THIS FROM 7272 to 3000
  type: NodePort
