apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  selector:
    app: demo-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000 # Your app listens on 3000
      nodePort: 30080  # <--- Explicitly define the NodePort here
                       # Must be in the 30000-32767 range and unique
  type: NodePort
